### ISSUE TITLE
可以加一个关于玩家在每个版本何时达成全战斗职业满级的榜单吗？

### ISSUE THREAD

**Issue by Aaron-cell979** [Cindy-Master/FFPVP-RANK#1]

**Comment by Cindy-Master** [comment]
I don't think you were successful in sending questions or suggestions. I'll help you close it first
我认为你是没有成功发送问题或者建议.先帮你关闭了

**Comment by Cindy-Master** [comment]
I only have the data of the full level of players here, and I haven't figured out how to rank it yet
玩家满级的数据我这里只有哪位玩家满级了,还未想好如何进行排名
Do you have any good suggestions?
你有什么好的建议吗?

**Comment by Cindy-Master** [comment]
我明白你的意思了 我有那个成就的记录 今明两天内会完成

**Comment by Cindy-Master** [comment]
做了90级的

**Comment by Aaron-cell979** [comment]
> 做了90级的

非常感谢，之后会考虑80级和70级吗？

**Comment by Cindy-Master** [comment]
80 70 60 50的 由于可以在同一时间达成 似乎不太有设置的必要

**Comment by Aaron-cell979** [comment]
如果可以的话希望能增加一个80级的，90和80这两个版本国服入坑人数较多，可能更多人愿意看

**Comment by Cindy-Master** [comment]
新增了80-50的 还加了点别的 记得清理一下浏览器缓存再看

**Comment by Aaron-cell979** [comment]
非常感谢，辛苦老师
