### ISSUE TITLE
可以加一个检测后面注册和后面开角色成就查询的功能吗

### ISSUE THREAD

**Issue by acctie-cyber** [Cindy-Master/FFPVP-RANK#2]
我的号没在榜上，也开了石之家，但是开榜单之前隐藏了 开榜单后才解锁（我以为等一天会有的  但是还是不在

**Comment by Cindy-Master** [comment]
是每隔48小时更新一次的，能提供一下你解开隐私的具体时间吗，几月几号几时，或者几月几号也行

**Comment by acctie-cyber** [comment]
不好意思，我不知道榜单是48小时刷新一次的，我解开隐私的时间是在9月4日晚上8.30左右解封的  我以为是按石之家每天中午12点刷新前一天数据的时间来算的

**Comment by Cindy-Master** [comment]
没事的没事的，我其实也想实时更新，但是石之家的访问速率限制太高了😭

**Comment by acctie-cyber** [comment]
谢谢！
