### ISSUE TITLE
可以加一个关于伊修加德重建的分数或者天穹圣人成就的榜单吗？

### ISSUE THREAD

**Issue by Rboill** [Cindy-Master/FFPVP-RANK#3]
这是重建分数排名的网址：https://actff1.web.sdo.com/project/20200601ishgardianranking/index.html#/result

**Comment by Cindy-Master** [comment]
天穹圣人不属于石之家的特殊成就，所以没有可以支持制作排行榜的数据

**Comment by Rboill** [comment]
好的，辛苦了
